### ISSUE TITLE
TypeError during kalman_filter.update with Numpy 1.25.*

### ISSUE THREAD

**Issue by jpchang-episci** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#473]
I get an error during kalman_filter.update call with numpy 1.25.*, but if I roll back to numpy 1.24.*, this error does not occur.

Thank you

**_Python 3.11
Numpy: 1.25
Filterpy: 1.4.5

 Traceback (most recent call last):
  File "/builds/alchemy/ta-2/service-pa-tracker/tracker_src/model/kalman_filter_model.py", line 297, in update
    self.kalman_filter.update(
  File "/home/python/.local/lib/python3.11/site-packages/filterpy/kalman/kalman_filter.py", line 545, in update
    self.SI = self.inv(self.S)
              ^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable_**

**Comment by jpchang-episci** [comment]
2023-07-03 21:49:29,603 WARNING  kalman_filter_model.py:309 kalman_filter.inv is not callable {'py/object': 'numpy._ArrayFunctionDispatcher', '__module__': 'numpy.linalg', '__name__': 'inv', '__qualname__': 'inv', '__doc__' : '\n    Compute the (multiplicative) inverse of a matrix.\n\n    Given a square matrix `a`, return the matrix `ainv` satisfying\n    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.\n\n    Parameters\n    ----------\n    a : (..., M, M) array_like\n        Matrix to be inverted.\n\n    Returns\n    -------\n    ainv : (..., M, M) ndarray or matrix\n        (Multiplicative) inverse of the matrix `a`.\n\n    Raises\n    ------\n    LinAlgError\n        If `a` is not square or inversion fails.\n\n    See Also\n    --------\n    scipy.linalg.inv : Similar function in SciPy.\n\n    Notes\n    -----\n\n    .. versionadded:: 1.8.0\n\n    Broadcasting rules apply, see the `numpy.linalg` documentation for\n    details.\n\n    Examples\n    --------\n    >>> from numpy.linalg import inv\n    >>> a = np.array([[1., 2.], [3., 4.]])\n    >>> ainv = inv(a)\n    >>> np.allclose(np.dot(a, ainv), np.eye(2))\n    True\n    >>> np.allclose(np.dot(ainv, a), np.eye(2))\n    True\n\n    If a is a matrix object, then the return value is a matrix as well:\n\n    >>> ainv = inv(np.matrix(a))\n    >>> ainv\n    matrix([[-2. ,  1. ],\n            [ 1.5, -0.5]])\n\n    Inverses of several matrices can be computed at once:\n\n    >>> a = np.array([[[1., 2.], [3., 4.]], [[1, 3], [3, 5]]])\n    >>> inv(a)\n    array([[[-2.  ,  1.  ],\n            [ 1.5 , -0.5 ]],\n           [[-1.25,  0.75],\n            [ 0.75, -0.25]]])\n\n    ', '__annotations__': {}, '__wrapped__': {'py/function': 'numpy.linalg.linalg.inv'}} pid:23
